export const userInputs_product = [
  {
    id: 1,
    label: "Name",
    type: "text",
    placeholder: "NTP",
    name: "productName",
  },
  {
    id: 2,
    label: "Price",
    type: "text",
    placeholder: "1.000.000",
    name: "price",
  },
  {
    id: 3,
    label: "Discount",
    type: "text",
    placeholder: "200.000",
    name: "discount",
  },
  {
    id: 4,
    label: "Stock",
    type: "text",
    placeholder: "15",
    name: "unitslnStock",
  },
  {
    id: 5,
    label: "Description",
    type: "text",
    placeholder: "",
    name: "descriptions",
  },
  {
    id: 6,
    label: "Alias",
    type: "text",
    placeholder: "",
    name: "alias",
  },
  {
    id: 7,
    label: "Bestseller",
    type: "boolen",
    placeholder: "",
    name: "bestSellers",
  },
  {
    id: 8,
    label: "Active",
    type: "boolen",
    placeholder: "",
    name: "active",
  },
  {
    id: 9,
    label: "HomeFlag",
    type: "boolen",
    placeholder: "",
    name: "homeFlag",
  },
];

export const productInputs_product = [
  {
    id: 1,
    label: "Name",
    type: "text",
    placeholder: "NTP",
    name: "productName",
  },
  {
    id: 2,
    label: "Price",
    type: "text",
    placeholder: "1.000.000",
    name: "price",
  },
  {
    id: 3,
    label: "Discount",
    type: "text",
    placeholder: "200.000",
    name: "discount",
  },
  {
    id: 4,
    label: "Stock",
    type: "text",
    placeholder: "15",
    name: "unitslnStock",
  },
  {
    id: 5,
    label: "Description",
    type: "text",
    placeholder: "",
    name: "descriptions",
  },
  {
    id: 6,
    label: "ShortDesc",
    type: "text",
    placeholder: "",
    name: "shortDesc",
  },
  {
    id: 7,
    label: "Alias",
    type: "text",
    placeholder: "",
    name: "alias",
  },
  
  {
    id: 8,
    label: "Bestseller",
    type: "boolean",
    placeholder: "",
    name: "bestSellers",
  },
  {
    id: 9,
    label: "Active",
    type: "boolean",
    placeholder: "",
    name: "active",
  },
  {
    id: 10,
    label: "HomeFlag",
    type: "boolean",
    placeholder: "",
    name: "homeFlag",
  },
  // {
  //   id: 8,
  //   label: "CategoryId",
  //   type: "text",
  //   placeholder: "",
  //   name: "catId",
  // },
];
